import subprocess
import os
from SCons.Script import DefaultEnvironment

env = DefaultEnvironment()

def get_git_version(project_dir):
    try:
        out = subprocess.check_output(
            [
                "git",
                "describe",
                "--tags",
                "--always",
                "--dirty=-dev",
                "--broken=-dev",
            ],
            cwd=project_dir,
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except Exception:
        return "unknown"


git_ver = get_git_version(env.get("PROJECT_DIR"))

header_dir = os.path.join(env.get("PROJECT_DIR"), "include")
os.makedirs(header_dir, exist_ok=True)
header_path = os.path.join(header_dir, "project_version.h")
hdr = []
hdr.append("// This file is auto-generated by scripts/git_version.py.\n")
hdr.append("// Please do not edit manually.\n")
hdr.append("#pragma once\n\n")
hdr.append("#define PROJECT_VER \"{0}\"\n".format(git_ver))
hdr.append("static const char PROJECT_VER_STR[] = PROJECT_VER;\n")

with open(header_path, "w", encoding="utf-8") as f:
    f.writelines(hdr)

print("[git_version] Wrote {0}".format(header_path))
